# Generated by Django 4.2.11 on 2024-07-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='csvs/')),
                ('date_column', models.CharField(max_length=100)),
                ('date_format', models.CharField(max_length=50)),
                ('demand_column', models.CharField(max_length=100)),
                ('forecast_days', models.IntegerField()),
                ('train_test_split', models.FloatField()),
            ],
        ),
    ]
