# Generated by Django 4.2.11 on 2024-07-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand_forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastingrequest',
            name='frequency',
            field=models.CharField(default='D', max_length=1),
            preserve_default=False,
        ),
    ]
