# Generated by Django 4.2.11 on 2024-06-14 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
