# Generated by Django 4.2.11 on 2024-06-14 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_score', '0003_matchplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings', models.IntegerField(choices=[(1, '1st Innings'), (2, '2nd Innings')])),
                ('over', models.IntegerField()),
                ('over_ball', models.IntegerField()),
                ('current_ball', models.DecimalField(decimal_places=1, max_digits=4)),
                ('batter_run', models.IntegerField()),
                ('extra_type', models.CharField(blank=True, choices=[('wide', 'Wide'), ('no_ball', 'No Ball'), ('bye', 'Bye'), ('leg_bye', 'Leg Bye'), ('penalty_runs', 'Penalty Runs')], max_length=20, null=True)),
                ('extra_run', models.IntegerField()),
                ('is_extra', models.BooleanField(default=False)),
                ('is_wicket', models.BooleanField(default=False)),
                ('wicket_type', models.CharField(blank=True, choices=[('bowled', 'Bowled'), ('caught', 'Caught'), ('lbw', 'LBW'), ('run_out', 'Run Out'), ('stumped', 'Stumped'), ('hit_wicket', 'Hit Wicket'), ('hit_ball_twice', 'Hit the Ball Twice'), ('obstructing_field', 'Obstructing the Field'), ('timed_out', 'Timed Out'), ('handled_ball', 'Handled the Ball')], max_length=20, null=True)),
                ('commentary', models.TextField(blank=True, null=True)),
                ('batter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batted_balls', to='cricket_score.player')),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_balls', to='cricket_score.team')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowled_balls', to='cricket_score.player')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_balls', to='cricket_score.team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls', to='cricket_score.match')),
                ('non_striker_batter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_striker_balls', to='cricket_score.player')),
                ('wicket_bowler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wicket_balls', to='cricket_score.player')),
                ('wicket_fielder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fielded_wickets', to='cricket_score.player')),
            ],
        ),
    ]
