# Generated by Django 4.2.11 on 2024-06-14 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_score', '0004_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='first_batting_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_batting_matches', to='cricket_score.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='second_batting_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_batting_matches', to='cricket_score.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='toss_won_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toss_won_matches', to='cricket_score.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='umpires',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ball',
            name='batter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batter', to='cricket_score.player'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='bowler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowler', to='cricket_score.player'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='extra_type',
            field=models.CharField(blank=True, choices=[('wide', 'Wide'), ('no_ball', 'No Ball'), ('bye', 'Bye'), ('leg_bye', 'Leg Bye'), ('penalty_runs', 'Penalty Runs')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ball',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='cricket_score.match'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='non_striker_batter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_striker', to='cricket_score.player'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='wicket_bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wicket_bowler', to='cricket_score.player'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='wicket_fielder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wicket_fielder', to='cricket_score.player'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='wicket_type',
            field=models.CharField(blank=True, choices=[('bowled', 'Bowled'), ('caught', 'Caught'), ('lbw', 'LBW'), ('run_out', 'Run Out'), ('stumped', 'Stumped'), ('hit_wicket', 'Hit Wicket'), ('hit_ball_twice', 'Hit the Ball Twice'), ('obstructing_field', 'Obstructing the Field'), ('timed_out', 'Timed Out'), ('handled_ball', 'Handled the Ball')], max_length=50, null=True),
        ),
    ]
