# Generated by Django 4.2.11 on 2024-06-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_score', '0005_match_first_batting_team_match_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('paused', 'Paused'), ('1st_innings_running', '1st Innings Running'), ('1st_innings_over', '1st Innings Over'), ('2nd_innings_running', '2nd Innings Running'), ('2nd_innings_over', '2nd Innings Over')], default='not_started', max_length=20),
        ),
    ]
