# Generated by Django 4.2.11 on 2024-06-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_score', '0006_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='batter_run',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ball',
            name='extra_run',
            field=models.IntegerField(blank=True),
        ),
    ]
