# Generated by Django 4.2.11 on 2024-06-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_score', '0007_alter_ball_batter_run_alter_ball_extra_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='batter_run',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ball',
            name='extra_run',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
