# Generated by Django 4.2.11 on 2024-06-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_score', '0008_alter_ball_batter_run_alter_ball_extra_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='next_ball',
            field=models.DecimalField(decimal_places=1, default=0.1, max_digits=4),
        ),
    ]
