# Generated by Django 4.2.11 on 2024-03-30 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Contact', 'Contact'), ('Lead', 'Lead'), ('Customer', 'Customer')], default='Contact', max_length=50)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='crm.contact')),
            ],
        ),
    ]
